---
title: "Assignment_One"
author: "Evan Trowbridge"
date: "4/24/2021"
output:
  pdf_document: default
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(readr)
library(janitor)
library(tidyverse)
library(skimr) # For reviewing data
library(plm) # For panel regressions
library(stargazer) # For nice regression tables
library(sf) # For spatial data
```

```{r message=FALSE, warning=FALSE, include=FALSE}
night_light_import <- read_csv("assignment1_nightlights.csv")

df_light <- night_light_import %>% clean_names()
```

Part A

```{r}
df_2a <- df_light %>% filter(date==2012)

# Figure 1: Population
df_2a %>%
  ggplot(aes(x = log_population, y = log_dmsp)) +
  geom_point() +
  labs(
    x = "Population (Logged)",
    y = "Nighlight Intensity (Logged)",
    title = "Figure 1: Nightlight Intensity by Population",
    subtitle = "All values are logged"
  )

# Figure 2: GDP
df_2a %>%
  ggplot(aes(x = log_gdp, y = log_dmsp)) +
  geom_point() +
  labs(
    x = "GDP (Logged)",
    y = "Nighlight Intensity (Logged)",
    title = "Figure 2: Nightlight Intensity by GDP",
    subtitle = "All values are logged"
  )

# Figure 2: Electricity Demand
df_2a %>%
  ggplot(aes(x = log_elec, y = log_dmsp)) +
  geom_point() +
  labs(
    x = "Electricity Demand (Logged)",
    y = "Nighlight Intensity (Logged)",
    title = "Figure 3: Nightlight Intensity by Electricity Demand",
    subtitle = "All values are logged"
  )

```

Part B

```{r question_2b}
df_2b <- df_light

# Using set.seed to may results reproducible
set.seed(123)

# Selecting the 150 countries
df_150_countries <- df_2b %>% 
  select(country) %>% 
  distinct() %>% 
  sample_n(150) %>% 
  mutate(training_group = TRUE)

df_2b <- left_join(df_2b, df_150_countries, by = "country") %>% 
  distinct() %>% 
  mutate(
    training_group = 
      if_else(training_group == TRUE, TRUE, FALSE, missing = FALSE),
    date = as_factor(date)) %>% 
  filter(
    !is.na(log_gdp) &
    !is.na(log_population) & 
    !is.na(log_dmsp))

# Converting to plm panel indexed dataframe
p_2b <- pdata.frame(df_2b, index  = c("date")) %>% 
  filter(
    !is.na(log_gdp) & 
    !is.na(log_population) & 
    !is.na(log_dmsp)) %>% 
  select(date, log_gdp, log_population, log_dmsp, training_group) 

# Dataframe for countries in training group
p_2b_150 <- p_2b %>% filter(training_group==TRUE)

# Dataframe for countries in prediction group
p_2b_30 <- p_2b %>% filter(training_group==FALSE) 

# Regression model
#   I use 0 as the intercept since this uses fixed effects
#   Reference: https://stackoverflow.com/questions/65702581/predict-out-of-sample-on-fixed-effects-model
gdp_mod <- plm(log_gdp ~ 0 + log_population + log_dmsp,
               data = p_2b_150,
               model = "within")

p_2b_30 <- predict(gdp_mod, newdata = p_2b_30) %>% 
  tibble() %>% 
  rename(pred_value = ".") %>%
  bind_cols(p_2b_30)

cor(p_2b_30$log_gdp, p_2b_30$pred_value)

p_2b_30 %>%
  ggplot(aes(x=pred_value, y =log_gdp)) +
  geom_point() +
  labs(
    x = "Predicted Value: GDP (Logged)",
    y = "Observed Value: GDP (Logged)",
    title = "Figure 4: Predicted Values and Observed Values",
    subtitle = "For 30 Countries Not in Training Data"
  )

```

```{r q2b_regression, results = "asis"}
stargazer(gdp_mod, title = "Results of 150-Country Sample", type = "latex")
```

```{r}
df_2c <- df_light

df_2c <- df_2c %>% 
  filter(
    !is.na(log_gdp) & 
    !is.na(dictator) & 
    !is.na(log_dmsp)) %>% 
  select(date, country, log_gdp, log_dmsp, dictator) 

# Converting to plm panel indexed dataframe
p_2c <- pdata.frame(df_2c) %>% 
  filter(
    !is.na(log_gdp) & 
    !is.na(dictator) & 
    !is.na(log_dmsp)) %>% 
  select(country, date, log_gdp, log_dmsp, dictator) 

gdp_mod_2c <- plm(log_gdp ~ log_dmsp * dictator,
               index = c("country", "date"),
               data = p_2c,
               model = "within")

summary(gdp_mod_2c)

df_2c %>% mutate(
  dictator_text = if_else(
    dictator == 1,
    "Dicator",
    "Not Dictator")) %>%
  ggplot(aes(x=log_dmsp, y =log_gdp)) +
  geom_point() +
  labs(
    x = "Nighlight Intensity (Logged)",
    y = "GDP (Logged)",
    title = "Figure 5: Relationship Between Nightlight Intensity and GDP",
    subtitle = "Comparing Between Governments With and Without Dictators"
  ) +
  facet_grid(cols=vars(dictator_text))


```

```{r q2c_regression, results = "asis"}
stargazer(gdp_mod_2c, title = "GDP Correlation with Nightlights and Dictatorial Government", type = "latex")
```

```{r}
india_shape <- st_read("india_nl.shp")

india_shape %>%
  ggplot(aes(fill = PERC_ILLT)) +
  geom_sf(color = NA) +
  scale_fill_viridis_c(
    option = "magma", 
    direction = -1,
    name = "% Illiterate") +
  theme_void() +
  labs(title = "Figure 6: Illiteracy in India by District")

india_shape %>%
  ggplot(aes(fill = NL)) +
  geom_sf(color = NA) +
  scale_fill_viridis_c(
    name = "Nightlight Brightness") +
  theme_void() +
  labs(title = "Figure 7: Nightlight in India by District")
```

```{r}
india_shape %>%
  ggplot(aes(x=NL, y =PERC_ILLT)) +
  geom_point() +
  stat_smooth(method = "lm", se = FALSE) +
  labs(
    x = "Nightlight Brightness",
    y = "% Illiterate",
    title = "Figure 8: Comparing Nightlight Brightness with Illiteracy Rates",
    subtitle = "By District in India"
  )
```

```{r}
state_gdp <- read_csv("state_gdp.csv")

df_avg_nl <- india_shape %>% 
  tibble() %>% 
  select(STATE_UT, NL) %>%
  group_by(STATE_UT) %>%
  mutate(avg_state_nl = mean(NL)) %>%
  ungroup() %>% 
  rename(StateName = STATE_UT) %>%
  select(StateName, avg_state_nl) %>%
  distinct() %>%
  mutate(StateName =
           if_else(StateName == "Tamilnadu",
                   "Tamil Nadu",
                   StateName)) %>%
  full_join(state_gdp) %>%
    filter(StateName != "India")

model_2f <- lm(GDP ~ avg_state_nl, data = df_avg_nl)

summary(model_2f)

df_avg_nl %>%
  ggplot(aes(x=avg_state_nl, y =GDP)) +
  geom_point() +
  stat_smooth(method = "lm", se = FALSE) +
  labs(
    x = "Nightlight Brightness",
    y = "GDP",
    title = "Figure 9: Comparing Nightlight Brightness with GDP",
    subtitle = "By State in India"
  )

df_avg_nl_darker <- df_avg_nl %>% filter(avg_state_nl < 1)

model_2f_darker <- lm(GDP ~ avg_state_nl, data = df_avg_nl_darker)

summary(model_2f_darker)

```

```{r q2f_regression, results = "asis"}
stargazer(model_2f, model_2f_darker, 
          title = "Indian State GDP Correlation with Nightlight Brightness",
          covariate.labels = "Avg. State Nightlight Brightness",
          dep.var.labels = "State GDP",
          column.labels = c("All States", "States With Brightness < 1"),
          type = "latex")
```

Questions: can my entity fixed effect for 2c just be a country and not the average gdp. The results seem the same

iS "NL" nightlight?